# Generated by Django 2.0.2 on 2018-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180310_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reminders',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
